export const CLIENT_SET = 'CLIENT_SET';
export const CLIENT_UNSET = 'CLIENT_UNSET';

export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const LOGOUT = 'LOGOUT';

export const SEARCH = 'SEARCH';
export const SEARCH_REQUESTING = 'SEARCH_REQUESTING';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_ERROR = 'SEARCH_REQUEST_ERROR';

export const MOVIES_REQUESTING = 'MOVIES_REQUESTING';
export const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS';
export const MOVIES_REQUEST_ERROR = 'MOVIES_REQUEST_ERROR';

export const MOVIE_DETAILS_REQUESTING = 'MOVIE_DETAILS_REQUESTING';
export const MOVIE_DETAILS_REQUEST_SUCCESS = 'MOVIE_DETAILS_REQUEST_SUCCESS';
export const MOVIE_DETAILS_REQUEST_ERROR = 'MOVIE_DETAILS_REQUEST_ERROR';

export const LIKE_REQUESTING = 'LIKE_REQUESTING';
export const LIKE_REQUEST_SUCCESS = 'LIKE_REQUEST_SUCCESS';
export const LIKE_REQUEST_ERROR = 'LIKE_REQUEST_ERROR';

export const UNLIKE_REQUESTING = 'UNLIKE_REQUESTING';
export const UNLIKE_REQUEST_SUCCESS = 'UNLIKE_REQUEST_SUCCESS';
export const UNLIKE_REQUEST_ERROR = 'UNLIKE_REQUEST_ERROR';
